baseURL = "https://graynk.space/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "graynk"

_merge = "none"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "graynk"
  email = "gray@graynk.space"
  description = "That's me"
  bio = "Nikita \nKarpukhin"
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There's nothing here."

  [params.contact]
    [params.contact.0]
      name = "GitHub"
      icon = "github"
      style = "fab"
      link = "https://github.com/graynk"
    [params.contact.1]
      name = "Telegram"
      icon = "telegram"
      style = "fab"
      link = "https://t.me/semifunctional"
    [params.contact.2]
      name = "Steam"
      icon = "steam"
      style = "fab"
      link = "https://steamcommunity.com/id/graynk"
    [params.contact.3]
      name = "HN"
      icon = "hacker-news-square"
      style = "fab"
      link = "/hn"
