baseURL = "https://graynk.space/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "graynk"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "graynk"
  email = "gray@graynk.space"
  description = "That's me"
  bio = "Nikita \nKarpukhin"
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There's nothing here."

  [params.contact]
    github = "https://github.com/graynk"
    telegram = "https://t.me/semifunctional"
    steam = "https://steamcommunity.com/id/graynk"
    hacker-news-square = "/hn"
    email = "gray@graynk.space"
